### ISSUE TITLE
ngl that was a good rat nice work

### ISSUE THREAD

**Issue by potatonuke10** [BedTrap/BedTrap-addon#1]

**Comment by EurekaEffect** [comment]
?

**Comment by potatonuke10** [comment]
https://github.com/Purple20/yoink-rat-2022/releases/download/Release/get-yoinked-for-free.jar

**Comment by potatonuke10** [comment]
that retard

**Comment by potatonuke10** [comment]
its in the relese

**Comment by EurekaEffect** [comment]
do you know what ISSUE category means?

**Comment by potatonuke10** [comment]
my issue was my mine craft acounts got stolen 
retard

**Comment by potatonuke10** [comment]
and it has u writen all over it

**Comment by EurekaEffect** [comment]
why should I care about your account?

вт, 5 июл. 2022 г., 20:15 potatonuke10 ***@***.***>:
