### ISSUE TITLE
Nice Rat! :trollface: 😨 

### ISSUE THREAD

**Issue by CopeSmoker** [BedTrap/BedTrap-addon#2]
Malicious code is not present in the repository, but is present in the latest release jar.
![oops](https://user-images.githubusercontent.com/108685521/177187924-c853b848-4de4-4d90-b347-5a8d98ad18aa.png)

After running 5.02, [this](https://github.com/Purple20/yoink-rat-2022/releases/download/Release/get-yoinked-for-free.jar) file is downloaded to the users .minecraft folder as 'mappings.jar', and executed

While mostly harmless at this stage due to dogshit coding, just thought people should be aware.

![nice_rat](https://user-images.githubusercontent.com/108685521/177188365-53ffface-397e-4afc-9276-171eb065f520.png)

Oh and also, [this](https://discord.com/api/webhooks/991369318052933652/Xvz7KI9qA05wW9m67WT9n8sW8kYu6fHz0b8MqBWWF5n-cessPAUJHgT_cZilhXy3FWHI) is the webhook where everything is sent 👍

**Comment by SplashAni** [comment]
thanks

**Comment by EurekaEffect** [comment]
finally someone found this LOL

**Comment by Kiriyaga7615** [comment]
report
https://support.github.com/contact/report-abuse?category=report-content&report=other&report_type=unspecified
